describe('logout',()=>{
  it('login',()=>{
    cy.login({email:'firadevianas@gmail.com',pass:'ekrut123'})
})
    it('Signout',()=>{
        cy.wait(1000)
        cy.get('.eds-navheader__profile').click()
          .get('.ant-dropdown-menu-item').eq(2).click()
        cy.url().should('eq','https://stg.ekrut.com/login')
    })
})